### ISSUE TITLE
Incompatible with safetensors serialization 

### ISSUE THREAD

**Issue by SunMarc** [huggingface/quanto#100]
`QTensor` class is not serializable with safetensors. This happens because it is subclass of `torch.Tensor` (using `torch.Tensor._make_wrapper_subclass`) and safetensors can't serialize a wrapper around a `torch.Tensor`. 

### Example

```python 
from quanto import QLinear, qint8
import torch
from safetensors.torch import save_file

linear = torch.nn.Linear(32, 32, bias=True)
qlinear = QLinear.from_module(linear, weights=qint8)
qlinear.freeze()
state_dict = qlinear.state_dict()
print(state_dict)

save_file(state_dict, "qlinear.safetensors")
```

### Traceback 
```
OrderedDict([('weight', QTensor(tensor([[-127,  -43],
        [-119, -127]], dtype=torch.int8), scale=tensor([[0.0051],
        [0.0039]]), public_dtype=torch.float32)), ('bias', tensor([-0.4707, -0.0726])), ('input_scale', tensor(1.)), ('output_scale', tensor(1.))])
Traceback (most recent call last):
  File "test_save_quanto.py", line 12, in <module>
    save_file(state_dict, "qlinear.safetensors")
  File "/home/marc/.venv/lib/python3.8/site-packages/safetensors/torch.py", line 282, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
safetensors_rust.SafetensorError: Error preparing tensor view: InvalidTensorView(F32, [2, 2], 0)
```

I faced another error before getting this traceback. I got that `untyped_storage` and `storage`methods are undefined for QTensor ( Since QTensor is a wrapper of a Tensor, the object has no data and it is expected that some field on the Tensor will be another Tensor. In the case of QTensor, we declare two tensors:  `_data` and `_scale`. ) 
So, I declared the following in QTensor for now to bypass the error: 
``` python
    def untyped_storage(self):
        # print(self._data.untyped_storage())
        return self._data.untyped_storage()

    def storage(self):
        return self._data.storage()
```
I think that the fix should be on quanto library side. We should try to create a state_dict that safetensors can actually serialize (only real tensors), just like how it was done in [BNB 4-bit](https://github.com/TimDettmers/bitsandbytes/pull/753/files). LMK what you think @dacorvo @younesbelkada 

cc @Narsil

More information on [_make_wrapper_subclass](https://dev-discuss.pytorch.org/t/whats-the-difference-between-torch-tensor-make-subclass-and-torch-tensor-make-wrapper-subclass/1839)

**Comment by dacorvo** [comment]
@SunMarc I agree with you our only option is to create an unwrapped state_dict since `safetensors` is not aware of the structure of wrapped tensors (maybe it could with the new `__tensor_flatten__` and `__tensor_unflatten__` but that's another story).

**Comment by dacorvo** [comment]
To obtain a state-dict without any subclasses in it, I think I we can do something directly in the `QModuleMixin`, overriding the `_save_to_state_dict` and `_load_from_state_dict` method.

`_save_to_state_dict`:

We would simply check if the weights is a subtensor (`isinstance(weights, Tensor) and type(weights)!= Tensor), and if so:
- call `weights.__tensor_flatten__` to get a dict of internal `Tensor` and metadata,
- recurse on the internal tensors until they are really `Tensor` (because they may be also `Tensor` subclasses),
- add everything along the way to the state dict with proper prefixes,
- for each `Tensor` subclass we add to the dict, remember its real class,

Note: don't forget to serialize also the scales.

`_load_from_state_dict`:

Gather all the `prefix.weight` stuff and find the actual class. Based on that, we can just recover everything we need and just call `Tensor.__unflatten__` to recreate the `Tensor`

I am probably missing a few details, but that's the idea.

@SunMarc @younesbelkada WDYT ?

**Comment by dacorvo** [comment]
Once we have that, we still don't have a `safetensor` serialization, but we are close:
- split the `state_dict` between `tensors` and `metadata` objects (like `dtype`, `orig_shape`, `bits` and whatnot),
- convert the metadata dict to use only strings (we will need hard-coded rules for each metadata),
- serialize(tensors, metadata).

And I think we're good.

**Comment by SunMarc** [comment]
Makes sense. Thanks for sharing your thoughts. Just one remark about the `state_dict` between `tensors` and `metadata` objects. I see that safetensors accept the `metadata` field but for pytorch `torch.save`, I don't think we can pass it ( if we want to also make it compatible `weight_only = True`). Another solution would be to pack/unpack the non tensor value into a tensor as done [here](https://github.com/TimDettmers/bitsandbytes/pull/753/files#:~:text=def%20pack_dict_to_tensor(-,source_dict)%3A,-%22%22%22).
