### ISSUE TITLE
How dose quanto support int8 conv2d and linear?

### ISSUE THREAD

**Issue by zhexinli** [huggingface/quanto#158]
Hi, I look into the code and didn't find any cuda kernel related to conv2d and linear. How did you implement the cuda backend for conv2d/linear? Thanks

**Comment by dacorvo** [comment]
It's a bit buried in the function/operator dispatch code but basically, the default algorithm for matrix multiplication is:
- if both weights and activations are int8, use torch._int_mm,
- otherwise dequantize to fp16/fp32 and do the operation.
For conv2d it is rather:
- if both weights and activations are int8, cast to float32 and use torch.mm,
- otherwise dequantize to fp16/fp32 and do the operation.

**Comment by zhexinli** [comment]
That explains. Thanks
